################################################################################
#
#   Section: Organizations
#
#   - This section defines the different organizational identities which will
#   be referenced later in the configuration.
#
################################################################################
Organizations:
  - &org1
    # DefaultOrg defines the organization which is used in the sampleconfig
    # of the fabric.git development environment
    Name: org1MSP
    # ID to load the MSP definition as
    ID: org1MSP
    MSPDir: organizations/peerOrganizations/s-node.de/msp
    Policies:
      Readers:
        Type: Signature
        Rule: "OR('org1MSP.admin', 'org1MSP.peer', 'org1MSP.client')"
      Writers:
        Type: Signature
        Rule: "OR('org1MSP.admin', 'org1MSP.client')"
      Admins:
        Type: Signature
        Rule: "OR('org1MSP.admin')"
      Endorsement:
        Type: Signature
        Rule: "OR('org1MSP.peer')"
    AnchorPeers:
      # AnchorPeers defines the location of peers which can be used
      # for cross org gossip communication.  Note, this value is only
      # encoded in the genesis block in the Application section context
      - Host: s-node.de
        Port: 30001
