apiVersion: v1
kind: Pod
metadata:
  name: scray-ledger-event-api
spec:
  containers:
    - name: event-rest-api
      image: scrayorg/event-rest-api:1.3
      volumeMounts:
        - name: secret-conf-vol
          mountPath: /etc/secret-conf-vol
  volumes:
    - name: secret-conf-vol
      secret:
        secretName: event-rest-api-i1
---
apiVersion: v1
kind: Service
metadata:
  name: event-rest-api-i1
  labels:
    run: event-rest-api-i1
spec:
  type: NodePort
  selector:
    app: event-rest-api-i1
  ports:
    - name: api-port
      port: 8080
      protocol: TCP