apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: scray-ledger-data-share-pv-claim 
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
