apiVersion: v1
kind: Service
metadata:
  name: hl-fabric-data-share-service3
  labels:
    run: hl-fabric-data-share-service3
spec:
  type: LoadBalancer 
  selector:
    app: hl-fabric-data-share
  ports:
    - name: webdav-port
      protocol: TCP
      port: 80
