apiVersion: v1
kind: Service
metadata:
  name: hl-fabric-cc-external-invoice-net
  labels:
    run: hl-fabric-cc-external-invoice-net
spec:
  type: NodePort
  selector:
    app: hl-fabric-cc-external-invoice-net
  ports:
    - name: chaincode
      port: 9999
      protocol: TCP