---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: orderer1
  labels:
    app: orderer1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: orderer1
  template:
    metadata:
      labels:
        app: orderer1
    spec:
      containers:
        - name: orderer1
          image:  hyperledger/fabric-orderer:2.2.1
          workingDir: /opt/gopath/src/github.com/hyperledger/fabric
          env:
          - name: ORDERER_GENERAL_LISTENADDRESS
            value: "0.0.0.0"
          - name: ORDERER_GENERAL_LISTENPORT
            value: "7050"         
          - name: ORDERER_GENERAL_GENESISMETHOD
            value: "file"
          - name: ORDERER_GENERAL_GENESISFILE
            value: "/var/hyperledger/orderer/orderer.genesis.block"  
          - name: ORDERER_GENERAL_LOCALMSPID
            value: "OrdererMSP"
          - name: ORDERER_GENERAL_LOCALMSPDIR
            value: "/var/hyperledger/orderer/msp"         
          - name: ORDERER_GENERAL_TLS_ENABLED
            value: "true"
          - name: ORDERER_GENERAL_TLS_PRIVATEKEY
            value: "/var/hyperledger/orderer/tls/server.key"              
          - name: ORDERER_GENERAL_TLS_CERTIFICATE
            value: "/var/hyperledger/orderer/tls/server.crt"
          - name: ORDERER_GENERAL_TLS_ROOTCAS
            value: "[/var/hyperledger/orderer/tls/ca.crt]"         
          - name: ORDERER_KAFKA_TOPIC_REPLICATIONFACTOR
            value: "1"
          - name: ORDERER_KAFKA_VERBOSE
            value: "true"  
          - name: ORDERER_GENERAL_CLUSTER_CLIENTCERTIFICATE
            value: "/var/hyperledger/orderer/tls/server.crt"
          - name: ORDERER_GENERAL_CLUSTER_CLIENTPRIVATEKEY
            value: "/var/hyperledger/orderer/tls/server.key"         
          - name: ORDERER_GENERAL_CLUSTER_ROOTCAS
            value: "[/var/hyperledger/orderer/tls/ca.crt]"        
          volumeMounts:
          - name: config
            mountPath: /var/hyperledger/orderer/orderer.genesis.block
            subPath: system-genesis-block/genesis.block
          - name: config
            mountPath: /var/hyperledger/orderer/msp
            subPath: organizations/ordererOrganizations/example.com/orderers/orderer.example.com/msp
          - name: config
            mountPath: /var/hyperledger/orderer/tls
            subPath: organizations/ordererOrganizations/example.com/orderers/orderer.example.com/tls
          - name: config
            mountPath: /var/hyperledger/production/orderer                  
      initContainers:
      - name: credential-loader
        image: alpine/git        
        command: ['/bin/sh', '-c']
        args: ['cd /mnt/hl-fabric-conf/ && wget https://mft.seeburger.de:443/portal-seefx/~public/M2E0NjUzMjEtZjY0Zi00MjExLWI0Y2EtNWNkYjUzMTIwYzlm?download -O config.zip &&  unzip config.zip']
        volumeMounts:
        - name: config
          mountPath: /mnt/hl-fabric-conf/
      volumes:
      - name: config
        emptyDir: {}