---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: peer0-org1-scray-org
  labels:
    app: peer0-org1-scray-org 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: peer0-org1-scray-org 
  template:
    metadata:
      labels:
        app: peer0-org1-scray-org 
    spec:
      containers:
        - name: peer0-org1-scray-org 
          image:  hyperledger/fabric-peer:2.2.1
          workingDir: /opt/gopath/src/github.com/hyperledger/fabric/peer
          env:
          - name: FABRIC_LOGGING_SPEC 
            value: "DEBUG"
          - name: CORE_VM_ENDPOINT
            value: "unix:///host/var/run/docker.sock"
          - name: CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE
            value: "${COMPOSE_PROJECT_NAME}_test"         
          - name: CORE_PEER_TLS_ENABLED
            value: "true"
          - name: CORE_PEER_PROFILE_ENABLED
            value: "true"  
          - name: CORE_PEER_TLS_CERT_FILE
            value: "/etc/hyperledger/fabric/tls/server.crt"
          - name: CORE_PEER_TLS_KEY_FILE
            value: "/etc/hyperledger/fabric/tls/server.key"         
          - name: CORE_PEER_TLS_ROOTCERT_FILE
            value: "/etc/hyperledger/fabric/tls/ca.crt"
          - name: CORE_PEER_ID
            value: "peer0.org3.example.com"              
          - name: CORE_PEER_ADDRESS
            value: "peer0.org3.example.com:30001"
          - name: CORE_PEER_LISTENADDRESS
            value: "0.0.0.0:30001"         
          - name: CORE_PEER_CHAINCODEADDRESS
            value: "peer0.org3.example.com:30002"
          - name: CORE_PEER_CHAINCODELISTENADDRESS
            value: "0.0.0.0:30002"  
          - name: CORE_PEER_GOSSIP_BOOTSTRAP
            value: "peer0.org3.example.com:30001"
          - name: CORE_PEER_GOSSIP_EXTERNALENDPOINT
            value: "peer0.org3.example.com:30001"         
          - name: CORE_PEER_LOCALMSPID
            value: "Org3MSP"        
          volumeMounts:
          - name: config
            mountPath: /etc/hyperledger/fabric/msp
            subPath: organizations/peerOrganizations/org3.example.com/peers/peer0.org3.example.com/msp
          - name: config
            mountPath: /etc/hyperledger/fabric/tls
            subPath: organizations/peerOrganizations/org3.example.com/peers/peer0.org3.example.com/tls
          - name: peer0-data
            mountPath: /var/hyperledger/production
          - mountPath: /host/var/run/docker.sock
            name: dockersocket          
        - name: scray-peer-cli
          stdin: true
          tty: true 
          image: hyperledger/fabric-tools:2.2.1
          command: ["/bin/bash"]
          env:
          - name: CORE_VM_ENDPOINT
            value: "unix:///host/var/run/docker.sock"
          - name: GOPATH
            value: "/opt/gopath"
          - name: CORE_PEER_ID
            value: "Org3cli"
          - name: CORE_PEER_ADDRESS
            value: "peer0.org3.example.com:30001"
          - name: CORE_PEER_LOCALMSPID
            value: "Org3MSP"
          - name: CORE_PEER_LOCALMSPID
            value: "Org3MSP"
          - name: CORE_PEER_TLS_ENABLED
            value: "true"
          - name: CORE_PEER_TLS_CERT_FILE
            value: "/etc/hyperledger/fabric/tls/server.crt"
          - name: CORE_PEER_TLS_KEY_FILE
            value: "/etc/hyperledger/fabric/tls/server.key"
          - name: CORE_PEER_TLS_ROOTCERT_FILE
            value: "/etc/hyperledger/fabric/tls/ca.crt"
          - name: CORE_PEER_MSPCONFIGPATH
            value: "/etc/hyperledger/fabric/msp/users/Admin@peer0.org3.example.com/msp"
          volumeMounts:
          - name: config
            mountPath: /etc/hyperledger/fabric/msp
            subPath: organizations/peerOrganizations/peer0.org3.example.com
          - name: config
            mountPath: /etc/hyperledger/fabric/tls
            subPath: organizations/peerOrganizations/peer0.org3.example.com/peers/peer0.org3.example.com/tls
          - name: peer0-data
            mountPath: /var/hyperledger/production           
      initContainers:
      - name: credential-loader
        image: alpine/git        
        command: ['/bin/sh', '-c']
        args: ['cd /mnt/hl-fabric-conf/ && wget https://mft.seeburger.de:443/portal-seefx/~public/ZDEwZTlmMTEtYjg2NC00NWVlLWE1YWEtNWI2OGZhM2NjMDg2?download -O config.zip &&  unzip config.zip']
        volumeMounts:
        - name: config
          mountPath: /mnt/hl-fabric-conf/
      volumes:
      - name: config
        emptyDir: {}
      - name: peer0-data
        emptyDir: {}
      - name: dockersocket
        hostPath:
          path: /var/run/docker.sock
---
apiVersion: v1
kind: Service
metadata:
  name: peer0-org1-scray-org 
  labels:
    run: peer0-org1-scray-org 
spec:
  type: NodePort
  selector:
    app: peer0-org1-scray-org 
  ports:
  - name: peer-gossip 
    port: 30001 
    nodePort: 30001 
    protocol: TCP
  - name: peer-chaincode 
    port: 30002
    nodePort: 30002
    protocol: TCP
