apiVersion: v1
kind: Pod
metadata:
  name: k8s-dockerfile-creator-example 
  labels:
    app: k8s-dockerfile-creator-example 
spec:
  containers:
  - name: ubuntu
    image: ubuntu:latest
    command: ["/bin/sleep", "3650d"]
    imagePullPolicy: IfNotPresent
    volumeMounts:
      - name: docker-push-vol 
        mountPath: "/workspace/"
  volumes:
    - name: docker-push-vol
      persistentVolumeClaim:
        claimName: docker-push-vol-claim
