apiVersion: v1
kind: Service
metadata:
  name: erc-1155
  labels:
    run: erc-1155
spec:
  type: NodePort
  selector:
    app: erc-1155
  ports:
    - name: chaincode
      port: 9999
      protocol: TCP
