apiVersion: v1
kind: Pod
metadata:
  name: hyperleder-fabric-invoice-example-rest-api 
spec:
  selector:
    matchLabels:
      app: hyperleder-fabric-invoice-example-rest-api
  template:
    metadata:
      labels:
        app: hyperleder-fabric-invoice-example-rest-api
    spec:
	  containers:
	  - name: hyperleder-fabric-invoice-example-rest-api 
	    image: scrayorg/hyperleder-fabric-invoice-example-rest-api 
	    volumeMounts:
	    - name: hyperleder-fabric-invoice-example-rest-api-config 
	      mountPath: /mnt/config
	  volumes:
	  - name: hyperleder-fabric-invoice-example-rest-api-config
	    emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: hyperleder-fabric-invoice-example-rest-api
  labels:
    run: hyperleder-fabric-invoice-example-rest-api
spec:
  type: NodePort
  selector:
    app: hyperleder-fabric-invoice-example-rest-api
  ports:
  - name: hyperleder-fabric-invoice-example-rest-api
    port: 8080
    nodePort: 30091
    protocol: TCP
