apiVersion: v1
kind: Service
metadata:
  name: hl-fabric-erc-721-example
  labels:
    run: hl-fabric-erc-721-example
spec:
  type: NodePort
  selector:
    app: hl-fabric-erc-721-example
  ports:
    - name: chaincode
      port: 9999
      protocol: TCP